name: CI - Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # curl_cffi uses libcurl; ensure present
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-xdist pytest-timeout

      - name: Run tests
        timeout-minutes: 25
        env:
          # Ensure tests don't require network unless mocked
          NO_NETWORK: '1'
          CI: 'true'
          GITHUB_ACTIONS: 'true'
          TESTING: 'true'
        run: |
          # Run tests with optimizations for CI environment
          # Skip slow/integration tests, use parallel execution, set timeouts
          pytest -q --tb=short --timeout=60 -m "not slow and not integration" \
                 -n auto --dist=worksteal \
                 --ignore=tests/claude/commands/test_orchestrate_integration.py \
                 --maxfail=5